use compilation database
Signed-off-by: Xuefeng, Ding <xuefeng.ding.physics@gmail.com>

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -13,6 +13,11 @@ jobs:
         with:
           submodules: recursive
 
+      - name: generate compilation database
+        run: |
+          rm -rf build
+          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+
       - uses: shenxianpeng/cpp-linter-action@refs/pull/42/head
         id: linter
         env:
@@ -24,3 +29,10 @@ jobs:
           database: build
           extensions: cc,cu
           files-changed-only: false
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Some files failed the linting checks!"
+          # for actual deployment
+          # run: exit 1
